const {
    USER_ALREADY_USED_REFERENCE_LINK, BET_DROP_LIMIT,
    USER_NOT_FOUND, NO_PERMISSIONS_TO_ACTION, BAD_REQUEST,
    AT_THIS_MOMENT_DROP_IS_NOT_ON_MARKET, PROMOCODE_NOT_VALID,
    DROP_ALREADY_SOLD, DROP_NOT_FOUND, TRADE_LINK_URL_NOT_FOUND,
    NOT_ENOUGH_MONEY, DROP_IS_NOT_MARKET_ABLE, INVENTORY_DATA_NOT_FOUND,
    PROMOCODE_ALREADY_EXIST, MESSAGE_NOT_FOUND, REFERENCE_LINK_NOT_FOUND,
    UNAUTHORIZED, PROMOCODE_ALREADY_USED, USER_NAME_DOES_NOT_INCLUDE_WINSKINS,
    USER_DEPOSIT_SUM_LESS_THAN_ONE_DOLLAR, USER_STEAM_LEVEL_LESS, USER_STEAM_NEED_INVENTORY_ITEM,
    WHEEL_FREE_SPIN_IS_ALREADY_USED, NOT_ENOUGH_DAILY_SUM, USER_IS_BLOCKED, USER_IS_NOT_BLOGGER,
    WITHDRAW_FOR_USER_IS_BLOCKED, CHAT_FOR_USER_IS_BLOCKED, MESSAGE_WAS_BLOCKED_BY_CENSORSHIP,
    FOR_OPEN_CHAT_USER_SHOULD_MAKE_DEPOSIT, LIMIT_MESSAGES_IN_SECOND, DROP_PRICE_ON_MARKET_IS_BIGGER_THAN_MAX_PRICE,
    USER_ALREADY_HAS_ACTIVE_SUPPORT_TICKET, TICKET_NOT_FOUND, TICKET_IS_ALREADY_CLOSE, IT_IS_NOT_USER_TICKET,
    REFERRAL_CODE_ALREADY_EXIST, NOT_FOUND, SOMETHING_WENT_WRONG, WAIT_NEXT_GAME, MIN_SUM_FOR_WITHDRAW,
    MIN_SUM_FOR_WITHDRAW_PROMO, USER_ALREADY_HAS_TRADE_LINK, SOME_USER_ALREADY_HAS_THIS_TRADE_LINK,
    MAX_WITHDRAW_COUNT, UPGRADE_DROP_IS_TOO_EXPENSIVE, UPGRADE_DROP_IS_TOO_CHEEP, USE_PROMO_IN_WHEEL,
    ALL_PROMOCODE_THIS_TYPE_HAVE_ALREADY_BEEN_USED, PROMOCODE_EXPIRED, UNEXPECTED, NEED_MORE_DEPOSIT,
    USER_HAS_ACTIVE_BET, TODAY_USER_ALREADY_USED_PROMO_THIS_TYPE, USER_AUTO_PICKUP_ALREADY_USED,
    USER_ALREADY_HAVE_BET, DROP_BET_LIMIT, DROP_IS_NOT_ALIVE, WAIT_WHEN_GAME_WILL_START,
    WITHDRAW_FOR_USER_IS_BLOCKED_NEED_PLAY_BACK_SUM, SERVER_RESTARTS, TRADE_LINK_INVALID,
    NOT_ENOUGH_BET_SUM, USER_IS_BLOCKED_ON_THIS_GAME, USER_DOESNT_HAS_CSGO_IN_STEAM,
    USER_DID_NOT_PLAY_CSGO_WITHIN_2_WEEKS, USER_NEED_MORE_FRIENDS_IN_STEAM, USE_ONLY_BONUS_DROP,
    MIN_STOP_FOR_BONUS_BETS_IS, USER_CAN_NOT_SELL_BONUS_DROP, LESS_THAN_DAY_IS_AFTER_YOUR_LAST_CALL,
    USER_ALREADY_RECEIVED_MAX_DONATION, USER_DID_NOT_REQUESTED_DONATION, MAX_SUM_FOR_THIS_DONATION_IS,
    MAX_SUM_FOR_DONATION_IS, USER_BALANCE_IS_LESS_THAN_DONATION_SUM, USER_DID_NOT_PLAY_ENOUGH_COUNT_GAMES,
    PLEASE_WAIT_NEXT_DRAW, STEAM_DID_NOT_PASS_USER, CAN_NOT_EXCHANGE_BONUS_DROP, MIN_ALLOW_SUM_FOR_BET,
    MAX_ALLOW_SUM_FOR_BET, USER_DEPOSIT_SUM_IS_NOT_ENOUGH, USER_ALREADY_EXIST,
    CASE_ALREADY_EXIST, CATEGORY_ALREADY_EXIST, CHANCE_IS_BIGGER_THAN_100,
    DROP_ALREADY_EXIST, CHANCE_IS_NOT_FULL, DROP_DUPLICATE, CATEGORY_NOT_EXIST,
    CAN_NOT_AVAILABLE_WITHOUT_CONTENT, NEED_LEVEL, CASE_WITH_LEVEL_ALREADY_EXIST,
    NOT_TOKEN, NOT_VALID_TOKEN
} = require('../constants/enums/statuses.enum');
// unexpected
module.exports = {
    UNEXPECTED: {
        message: UNEXPECTED,
        code: 'UNEXPECTED'
    },

    // Not found
    NOT_FOUND: {
        message: NOT_FOUND,
        code: 'NOT_FOUND'
    },

    USER_NOT_FOUND: {
        message: USER_NOT_FOUND,
        code: 'USER_NOT_FOUND'
    },

    INVENTORY_DATA_NOT_FOUND: {
        message: INVENTORY_DATA_NOT_FOUND,
        code: 'INVENTORY_DATA_NOT_FOUND'
    },

    DROP_NOT_FOUND: {
        message: DROP_NOT_FOUND,
        code: 'DROP_NOT_FOUND'
    },

    TRADE_LINK_URL_NOT_FOUND: {
        message: TRADE_LINK_URL_NOT_FOUND,
        code: 'TRADE_LINK_URL_NOT_FOUND'
    },

    AT_THIS_MOMENT_DROP_IS_NOT_ON_MARKET: {
        message: AT_THIS_MOMENT_DROP_IS_NOT_ON_MARKET,
        code: 'AT_THIS_MOMENT_DROP_IS_NOT_ON_MARKET'
    },

    USER_DID_NOT_REQUESTED_DONATION: {
        message: USER_DID_NOT_REQUESTED_DONATION,
        code: 'USER_DID_NOT_REQUESTED_DONATION'
    },

    USER_DID_NOT_PLAY_ENOUGH_COUNT_GAMES: {
        message: USER_DID_NOT_PLAY_ENOUGH_COUNT_GAMES,
        code: 'USER_DID_NOT_PLAY_ENOUGH_COUNT_GAMES'
    },

    PLEASE_WAIT_NEXT_DRAW: {
        message: PLEASE_WAIT_NEXT_DRAW,
        code: 'PLEASE_WAIT_NEXT_DRAW'
    },

    USER_BALANCE_IS_LESS_THAN_DONATION_SUM: {
        message: USER_BALANCE_IS_LESS_THAN_DONATION_SUM,
        code: 'USER_BALANCE_IS_LESS_THAN_DONATION_SUM'
    },

    MESSAGE_NOT_FOUND: {
        message: MESSAGE_NOT_FOUND,
        code: 'MESSAGE_NOT_FOUND'
    },

    REFERENCE_LINK_NOT_FOUND: {
        message: REFERENCE_LINK_NOT_FOUND,
        code: 'REFERENCE_LINK_NOT_FOUND'
    },

    TICKET_NOT_FOUND: {
        message: TICKET_NOT_FOUND,
        code: 'TICKET_NOT_FOUND'
    },

    // Bad request
    BAD_REQUEST: {
        message: BAD_REQUEST,
        code: 'BAD_REQUEST'
    },

    NOT_TOKEN: {
        message: NOT_TOKEN,
        code: 'NOT_TOKEN'
    },

    NOT_VALID_TOKEN: {
        message: NOT_VALID_TOKEN,
        code: 'NOT_VALID_TOKEN'
    },

    CHANCE_IS_BIGGER_THAN_100: {
        message: CHANCE_IS_BIGGER_THAN_100,
        code: 'CHANCE_IS_BIGGER_THAN_100'
    },

    CAN_NOT_AVAILABLE_WITHOUT_CONTENT: {
        message: CAN_NOT_AVAILABLE_WITHOUT_CONTENT,
        code: 'CAN_NOT_AVAILABLE_WITHOUT_CONTENT'
    },

    DROP_DUPLICATE: {
        message: DROP_DUPLICATE,
        code: 'DROP_DUPLICATE'
    },

    STEAM_DID_NOT_PASS_USER: {
        message: STEAM_DID_NOT_PASS_USER,
        code: 'STEAM_DID_NOT_PASS_USER'
    },

    LESS_THAN_DAY_IS_AFTER_YOUR_LAST_CALL: {
        message: LESS_THAN_DAY_IS_AFTER_YOUR_LAST_CALL,
        code: 'LESS_THAN_DAY_IS_AFTER_YOUR_LAST_CALL'
    },

    USER_DEPOSIT_SUM_IS_NOT_ENOUGH: {
        message: USER_DEPOSIT_SUM_IS_NOT_ENOUGH,
        code: 'USER_DEPOSIT_SUM_IS_NOT_ENOUGH'
    },

    USER_ALREADY_RECEIVED_MAX_DONATION: {
        message: USER_ALREADY_RECEIVED_MAX_DONATION,
        code: 'USER_ALREADY_RECEIVED_MAX_DONATION'
    },

    MAX_SUM_FOR_THIS_DONATION_IS: {
        message: MAX_SUM_FOR_THIS_DONATION_IS,
        code: 'MAX_SUM_FOR_THIS_DONATION_IS'
    },

    MAX_SUM_FOR_DONATION_IS: {
        message: MAX_SUM_FOR_DONATION_IS,
        code: 'MAX_SUM_FOR_DONATION_IS'
    },

    USER_IS_BLOCKED_ON_THIS_GAME: {
        message: USER_IS_BLOCKED_ON_THIS_GAME,
        code: 'USER_IS_BLOCKED_ON_THIS_GAME'
    },

    USE_ONLY_BONUS_DROP: {
        message: USE_ONLY_BONUS_DROP,
        code: 'USE_ONLY_BONUS_DROP'
    },

    MIN_STOP_FOR_BONUS_BETS_IS: {
        message: MIN_STOP_FOR_BONUS_BETS_IS,
        code: 'MIN_STOP_FOR_BONUS_BETS_IS'
    },

    SERVER_RESTARTS: {
        message: SERVER_RESTARTS,
        code: 'SERVER_RESTARTS',
    },

    NOT_ENOUGH_MONEY: {
        message: NOT_ENOUGH_MONEY,
        code: 'NOT_ENOUGH_MONEY',
    },

    NOT_ENOUGH_BET_SUM: {
        message: NOT_ENOUGH_BET_SUM,
        code: 'NOT_ENOUGH_BET_SUM',
    },

    UPGRADE_DROP_IS_TOO_CHEEP: {
        message: UPGRADE_DROP_IS_TOO_CHEEP,
        code: 'UPGRADE_DROP_IS_TOO_CHEEP',
    },

    UPGRADE_DROP_IS_TOO_EXPENSIVE: {
        message: UPGRADE_DROP_IS_TOO_EXPENSIVE,
        code: 'UPGRADE_DROP_IS_TOO_EXPENSIVE',
    },

    DROP_ALREADY_SOLD: {
        message: DROP_ALREADY_SOLD,
        code: 'DROP_ALREADY_SOLD',
    },

    USER_CAN_NOT_SELL_BONUS_DROP: {
        message: USER_CAN_NOT_SELL_BONUS_DROP,
        code: 'USER_CAN_NOT_SELL_BONUS_DROP',
    },

    USER_HAS_ACTIVE_BET: {
        message: USER_HAS_ACTIVE_BET,
        code: 'USER_HAS_ACTIVE_BET',
    },

    DROP_PRICE_ON_MARKET_IS_BIGGER_THAN_MAX_PRICE: {
        message: DROP_PRICE_ON_MARKET_IS_BIGGER_THAN_MAX_PRICE,
        code: 'DROP_PRICE_ON_MARKET_IS_BIGGER_THAN_MAX_PRICE',
    },

    USE_PROMO_IN_WHEEL: {
        message: USE_PROMO_IN_WHEEL,
        code: 'USE_PROMO_IN_WHEEL',
    },

    ALL_PROMOCODE_THIS_TYPE_HAVE_ALREADY_BEEN_USED: {
        message: ALL_PROMOCODE_THIS_TYPE_HAVE_ALREADY_BEEN_USED,
        code: 'ALL_PROMOCODE_THIS_TYPE_HAVE_ALREADY_BEEN_USED',
    },

    PROMOCODE_EXPIRED: {
        message: PROMOCODE_EXPIRED,
        code: 'PROMOCODE_EXPIRED',
    },

    PROMOCODE_NOT_VALID: {
        message: PROMOCODE_NOT_VALID,
        code: 'PROMOCODE_NOT_VALID',
    },

    PROMOCODE_ALREADY_EXIST: {
        message: PROMOCODE_ALREADY_EXIST,
        code: 'PROMOCODE_ALREADY_EXIST',
    },

    CASE_ALREADY_EXIST: {
        message: CASE_ALREADY_EXIST,
        code: 'CASE_ALREADY_EXIST',
    },

    CHANCE_IS_NOT_FULL: {
        message: CHANCE_IS_NOT_FULL,
        code: 'CHANCE_IS_NOT_FULL',
    },

    DROP_ALREADY_EXIST: {
        message: DROP_ALREADY_EXIST,
        code: 'DROP_ALREADY_EXIST',
    },

    CATEGORY_ALREADY_EXIST: {
        message: CATEGORY_ALREADY_EXIST,
        code: 'CATEGORY_ALREADY_EXIST',
    },

    CATEGORY_NOT_EXIST: {
        message: CATEGORY_NOT_EXIST,
        code: 'CATEGORY_NOT_EXIST',
    },

    NEED_LEVEL: {
        message: NEED_LEVEL,
        code: 'NEED_LEVEL',
    },

    CASE_WITH_LEVEL_ALREADY_EXIST: {
        message: CASE_WITH_LEVEL_ALREADY_EXIST,
        code: 'CASE_WITH_LEVEL_ALREADY_EXIST',
    },

    BET_DROP_LIMIT: {
        message: BET_DROP_LIMIT,
        code: 'BET_DROP_LIMIT',
    },

    WAIT_NEXT_GAME: {
        message: WAIT_NEXT_GAME,
        code: 'WAIT_NEXT_GAME',
    },

    PROMOCODE_ALREADY_USED: {
        message: PROMOCODE_ALREADY_USED,
        code: 'PROMOCODE_ALREADY_USED',
    },

    TODAY_USER_ALREADY_USED_PROMO_THIS_TYPE: {
        message: TODAY_USER_ALREADY_USED_PROMO_THIS_TYPE,
        code: 'TODAY_USER_ALREADY_USED_PROMO_THIS_TYPE',
    },

    USER_NAME_DOES_NOT_INCLUDE_WINSKINS: {
        message: USER_NAME_DOES_NOT_INCLUDE_WINSKINS,
        code: 'USER_NAME_DOES_NOT_INCLUDE_WINSKINS',
    },

    WHEEL_TIME_LIMIT: {
        code: 'WHEEL_TIME_LIMIT',
    },

    USER_DEPOSIT_SUM_LESS_THAN_ONE_DOLLAR: {
        message: USER_DEPOSIT_SUM_LESS_THAN_ONE_DOLLAR,
        code: 'USER_DEPOSIT_SUM_LESS_THAN_ONE_DOLLAR',
    },

    USER_STEAM_LEVEL_LESS: {
        message: USER_STEAM_LEVEL_LESS,
        code: 'USER_STEAM_LEVEL_LESS',
    },

    USER_DOESNT_HAS_CSGO_IN_STEAM: {
        message: USER_DOESNT_HAS_CSGO_IN_STEAM,
        code: 'USER_DOESNT_HAS_CSGO_IN_STEAM',
    },

    USER_DID_NOT_PLAY_CSGO_WITHIN_2_WEEKS: {
        message: USER_DID_NOT_PLAY_CSGO_WITHIN_2_WEEKS,
        code: 'USER_DID_NOT_PLAY_CSGO_WITHIN_2_WEEKS',
    },

    USER_NEED_MORE_FRIENDS_IN_STEAM: {
        message: USER_NEED_MORE_FRIENDS_IN_STEAM,
        code: 'USER_NEED_MORE_FRIENDS_IN_STEAM',
    },

    USER_ALREADY_HAS_TRADE_LINK: {
        message: USER_ALREADY_HAS_TRADE_LINK,
        code: 'USER_ALREADY_HAS_TRADE_LINK',
    },

    USER_ALREADY_EXIST: {
        message: USER_ALREADY_EXIST,
        code: 'USER_ALREADY_EXIST',
    },

    SOME_USER_ALREADY_HAS_THIS_TRADE_LINK: {
        message: SOME_USER_ALREADY_HAS_THIS_TRADE_LINK,
        code: 'SOME_USER_ALREADY_HAS_THIS_TRADE_LINK',
    },

    TRADE_LINK_INVALID: {
        message: TRADE_LINK_INVALID,
        code: 'TRADE_LINK_INVALID',
    },

    USER_STEAM_NEED_INVENTORY_ITEM: {
        message: USER_STEAM_NEED_INVENTORY_ITEM,
        code: 'USER_STEAM_NEED_INVENTORY_ITEM',
    },

    WHEEL_FREE_SPIN_IS_ALREADY_USED: {
        message: WHEEL_FREE_SPIN_IS_ALREADY_USED,
        code: 'WHEEL_FREE_SPIN_IS_ALREADY_USED',
    },

    NOT_ENOUGH_DAILY_SUM: {
        message: NOT_ENOUGH_DAILY_SUM,
        code: 'NOT_ENOUGH_DAILY_SUM',
    },

    USER_ALREADY_HAS_ACTIVE_SUPPORT_TICKET: {
        message: USER_ALREADY_HAS_ACTIVE_SUPPORT_TICKET,
        code: 'USER_ALREADY_HAS_ACTIVE_SUPPORT_TICKET',
    },

    REFERRAL_CODE_ALREADY_EXIST: {
        message: REFERRAL_CODE_ALREADY_EXIST,
        code: 'REFERRAL_CODE_ALREADY_EXIST',
    },

    // Forbidden
    FORBIDDEN_NO_PERMISSIONS: {
        message: NO_PERMISSIONS_TO_ACTION,
        code: 'FORBIDDEN_NO_PERMISSIONS'
    },

    DROP_IS_NOT_MARKET_ABLE: {
        message: DROP_IS_NOT_MARKET_ABLE,
        code: 'DROP_IS_NOT_MARKET_ABLE'
    },

    USER_ALREADY_USED_REFERENCE_LINK: {
        message: USER_ALREADY_USED_REFERENCE_LINK,
        code: 'USER_ALREADY_USED_REFERENCE_LINK'
    },

    UNAUTHORIZED: {
        message: UNAUTHORIZED,
        code: 'UNAUTHORIZED'
    },

    USER_IS_BLOCKED: {
        message: USER_IS_BLOCKED,
        code: 'USER_IS_BLOCKED'
    },

    USER_IS_NOT_BLOGGER: {
        message: USER_IS_NOT_BLOGGER,
        code: 'USER_IS_NOT_BLOGGER'
    },

    CAN_NOT_EXCHANGE_BONUS_DROP: {
        message: CAN_NOT_EXCHANGE_BONUS_DROP,
        code: 'CAN_NOT_EXCHANGE_BONUS_DROP'
    },

    WITHDRAW_FOR_USER_IS_BLOCKED: {
        message: WITHDRAW_FOR_USER_IS_BLOCKED,
        code: 'WITHDRAW_FOR_USER_IS_BLOCKED'
    },

    WITHDRAW_FOR_USER_IS_BLOCKED_NEED_PLAY_BACK_SUM: {
        message: WITHDRAW_FOR_USER_IS_BLOCKED_NEED_PLAY_BACK_SUM,
        code: 'WITHDRAW_FOR_USER_IS_BLOCKED_NEED_PLAY_BACK_SUM'
    },

    CHAT_FOR_USER_IS_BLOCKED: {
        message: CHAT_FOR_USER_IS_BLOCKED,
        code: 'CHAT_IS_BLOCKED_FOR_USER',
    },

    MESSAGE_WAS_BLOCKED_BY_CENSORSHIP: {
        message: MESSAGE_WAS_BLOCKED_BY_CENSORSHIP,
        code: 'MESSAGE_WAS_BLOCKED_BY_CENSORSHIP',
    },

    FOR_OPEN_CHAT_USER_SHOULD_MAKE_DEPOSIT: {
        message: FOR_OPEN_CHAT_USER_SHOULD_MAKE_DEPOSIT,
        code: 'FOR_OPEN_CHAT_USER_SHOULD_MAKE_DEPOSIT',
    },

    LIMIT_MESSAGES_IN_SECOND: {
        message: LIMIT_MESSAGES_IN_SECOND,
        code: 'LIMIT_MESSAGES_IN_SECOND',
    },

    TICKET_IS_ALREADY_CLOSE: {
        message: TICKET_IS_ALREADY_CLOSE,
        code: 'TICKET_IS_ALREADY_CLOSE'
    },

    IT_IS_NOT_USER_TICKET: {
        message: IT_IS_NOT_USER_TICKET,
        code: 'IT_IS_NOT_USER_TICKET'
    },

    SOMETHING_WENT_WRONG: {
        message: SOMETHING_WENT_WRONG,
        code: 'SOMETHING_WENT_WRONG'
    },

    MIN_SUM_FOR_WITHDRAW: {
        message: MIN_SUM_FOR_WITHDRAW,
        code: 'MIN_SUM_FOR_WITHDRAW'
    },

    MIN_SUM_FOR_WITHDRAW_PROMO: {
        message: MIN_SUM_FOR_WITHDRAW_PROMO,
        code: 'MIN_SUM_FOR_WITHDRAW_PROMO'
    },

    NEED_MORE_DEPOSIT: {
        message: NEED_MORE_DEPOSIT,
        code: 'NEED_MORE_DEPOSIT'
    },

    MAX_WITHDRAW_COUNT: {
        message: MAX_WITHDRAW_COUNT,
        code: 'MAX_WITHDRAW_COUNT'
    },

    USER_AUTO_PICKUP_ALREADY_USED: {
        message: USER_AUTO_PICKUP_ALREADY_USED,
        code: 'USER_AUTO_PICKUP_ALREADY_USED'
    },

    USER_ALREADY_HAVE_BET: {
        message: USER_ALREADY_HAVE_BET,
        code: 'USER_ALREADY_HAVE_BET'
    },

    DROP_BET_LIMIT: {
        message: DROP_BET_LIMIT,
        code: 'DROP_BET_LIMIT'
    },

    DROP_IS_NOT_ALIVE: {
        message: DROP_IS_NOT_ALIVE,
        code: 'DROP_IS_NOT_ALIVE'
    },

    WAIT_WHEN_GAME_WILL_START: {
        message: WAIT_WHEN_GAME_WILL_START,
        code: 'WAIT_WHEN_GAME_WILL_START'
    },

    MAX_ALLOW_SUM_FOR_BET: {
        message: MAX_ALLOW_SUM_FOR_BET,
        code: 'MAX_ALLOW_SUM_FOR_BET'
    },

    MIN_ALLOW_SUM_FOR_BET: {
        message: MIN_ALLOW_SUM_FOR_BET,
        code: 'MIN_ALLOW_SUM_FOR_BET'
    },
};
